### ISSUE TITLE
[Feedback] The Quest for water

### ISSUE THREAD

**Issue by tjsd** [rafacost/TheLangoliers#1]
So I have been playing this pack 4 hours tonight, last 2 hours I have been idle. I need water to do anything, and only way to get it is with cactus. It grows so sloooow. It has not rained,and I am in plains biome so it should unless you have disabled it. For the sake of progress I sugest you have a task where people hand in 1 cactus and get 4 back or something to speed  up this process.

**Comment by rafacost** [comment]
Hi! There is an easier way to get water... 
[SPOILER]Look at Pam's Harvestcraft[/SPOILER]

**Comment by tjsd** [comment]
If you are thinking of the water barrel, that requires 6 of a ingot, to get that many ingots you probably need a cobble gen to get enough gravel to sift that.

**Comment by rafacost** [comment]
Yeah, I will probably create the quest as you suggested. But you can get the 6 Iron for the Barrels if you get 64 Dusts, or 64 Sand or 64 Gravel, or even better the 64 Compressed Cobble, from the basics reward bags. Thats how I did it on all test worlds that I played.

**Comment by tjsd** [comment]
Yes, I got gravel and dust from 2 quests eventually. And I was able to create it, but since skyblocks are all about that initial lava bucket for a cobble gen I feel it is a bit to "random" if you get it or not.

**Comment by rafacost** [comment]
Version Alpha 0.21, has included a repeatable quest, where you can trade 4 Cactus Juices, for 1 Bucket of Water.
